### ISSUE TITLE
感谢作者,很棒的一个库, 提个小小的建议.

### ISSUE THREAD

**Issue by MQL9011** [faimin/ZDFlexLayoutKit#1]
希望能支持类似 swift版 [https://github.com/layoutBox/FlexLayout](FlexLayout)的链式调用.

我之前用过另一个OC版本的[https://github.com/guangmingzizai/FlexLayout-OC](FlexLayout-OC),可惜这个库不更新,而且和swift版有冲突.

希望作者加油维护!

**Comment by faimin** [comment]
> 希望能支持类似 swift版 [https://github.com/layoutBox/FlexLayout](FlexLayout)的链式调用.
> 
> 我之前用过另一个OC版本的[https://github.com/guangmingzizai/FlexLayout-OC](FlexLayout-OC),可惜这个库不更新,而且和swift版有冲突.
> 
> 希望作者加油维护!

非常感谢您的认可与建议，后续有精力了会考虑。目前这个`repo`也是支持在`Swift` 中使用的，只是没有纯 `Swift` 接口那么优雅

**Comment by faimin** [comment]
已添加对`Swift`语法的支持

```swift
let view = UIView()
view.zds.makeFlexLayout {
     $0.width(100).height(50%)
}
```
