### ISSUE TITLE
视图重叠

### ISSUE THREAD

**Issue by BlankConan** [faimin/ZDFlexLayoutKit#3]
<img width="353" alt="x" src="https://user-images.githubusercontent.com/38722095/122873799-cded3f80-d364-11eb-92b3-edb9e5550342.png">

**Comment by faimin** [comment]
你的是什么环境 或者如何复现 ？我这显示正常

![image](https://user-images.githubusercontent.com/8207436/123198281-660f3400-d4df-11eb-8373-bac8ac8fe6bb.png)

**Comment by BlankConan** [comment]
点击又下角的按钮的时候出现的

**Comment by BlankConan** [comment]
Xcode 12.5 模拟器用的是 iPhone 11 iOS14的系统吧

**Comment by faimin** [comment]
还是无法复现，辛苦有时间的时候再帮忙确认下 @BlankConan

**Comment by BlankConan** [comment]
我这边换升级xcode和模拟器了，也复现不了了，我记得之前点击有个地方，会隐藏和显示认证红娘，就是那个东西出现的

**Comment by BlankConan** [comment]
点点带认证的那些cell的聊天按钮，然后滑动滑动，就复现了

**Comment by faimin** [comment]
修了，感谢反馈

**Comment by faimin** [comment]
这个issue我先关掉了，如果还有问题，我再重新打开
